---
title: "Final Project"
author: "Matti Harrison"
date: "10/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Does it matter if you choose a Private or Public University?
I want to compare the top public and private Universities to see if there is a difference in average earnings after graduation.  For my initial comparisons I will see the differences in tuition vs. debt ratio.  Then I will continue on to the most common major for each school, this usually predicts the wage.  Then I will compare the average earnings between the different schools.  

I originally wanted to get the #1 private/public university and then also the #50 school for each to be able to standardize.  #1 schools are in the top for overall school so #50 will be able to see a clear difference.
 
I am not sure if there is a way to get data from all public/private universities into 1 dataset.

private- (1) Harvard (50) Wake Forest University

public- (1) UC Berkeley (50) University of Oregon




